version: '3'
services:
  bigeny-api:
    container_name: bigeny-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - uploads:/uploads
  postgres:
    container_name: bigeny-base
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345654321'
      POSTGRES_DB: 'bigeny_api_dev'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  uploads:
    driver: local
  db:
    driver: local
