version: '3'
services:
  bigeny-api:
    container_name: bigeny-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@176.126.103.27:5432/bigeny_api_dev?schema=public
    env_file:
      - .env
  postgres:
    container_name: bigeny-base
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: 'bigeny_api_dev'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
