version: '3'
services:
  # bigeny-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: bigeny-api
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   env_file:
  #     - .env
  database:
    container_name: bigeny_mysql
    image: mysql:8
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'bigeny_api_dev'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Passw0rd'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - bigeny-db:/var/lib/mysql
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'

volumes:
  bigeny-db:
