version: '3'
services:
  bigeny-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bigeny-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'bigeny_api_dev'
